version: '3'
services:
  react_app:
    container_name: react_app
    build: ./
    volumes:
      - build_react:/var/www/html

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - react_app

volumes:
  build_react:
